### ISSUE TITLE
Loader 报错

### ISSUE THREAD

**Issue by NN708** [obstudio/ThuliumMusic-Parser#1]
在解析 *Egoist*、*Necro Fantasia*、*Sumizome Sakura* 时出现此错误。

报错信息：
```
\library\Parser\Loader.js:115
this.mergeMeta(result, src);
^
TypeError: this.mergeMeta is not a function
```

**Comment by jjyyxx** [comment]
与L70的assign相关，assign不复制原型链，导致tmAPI实际没有mergeMeta方法

**Comment by shigma** [comment]
经检查, *Necro Fantasia* 和 *Sumizome Sakura* 的确存在上述问题, 正在着手修复. 但是 *Egoist* 并没有看到你所说的情况. 能再次给出该文件的报错信息吗?
